### ISSUE TITLE
Unable to get UndoRedo plugin

### ISSUE THREAD

**Issue by ottosson** [handsontable/angular-handsontable#159]
I want to clear the undo/redo history of my table using the clear method of the UndoRedo plugin.
But it doesn't seem to exist any UndoRedo plugin, but it's in the docs, so I don't know if there is something wrong with the docs or the library itself.

I expected it to look something like this:
`const history = this.myTable.getPlugin("undoRedo");`

What am I missing?

Thanks!

### Your environment
* Angular version: 8
* Handsontable version: 7.0.2
* Wrapper version: 5.0.0
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @ottosson 

currently, undoRedo is available straight for the instance.
Here's a corresponsind subject on vanilla https://github.com/handsontable/handsontable/issues/4192

**Comment by ottosson** [comment]
Ah, it seems to be possible to access undoRedo but it doesn't seem to exist in the typings:
https://stackblitz.com/edit/handsontable-angular-qcfaqp?file=app%2Fapp.component.ts

**Comment by AMBudnik** [comment]
Yes.. that is a second thing. I think that we should mention it and I do not see the handsontable/handsontable#4192 being scheduled for the next two months.

**Comment by wojciechczerniak** [comment]
@pnowak @AMBudnik UndoRedo was added to `handsontable.d.ts` for v8. So this should be solved?

**Comment by pnowak** [comment]
After updated Angular wrapper and Handsontable `undoRedo` exists in the typings.

Could you @ottosson confirm?

**Comment by ottosson** [comment]
When is the angular wrapper being updated to support v8.x of Handsontable? The latest version of the wrapper(5.1.1) still does not contain the typings for `undoRedo`

**Comment by pnowak** [comment]
Hi @ottosson 

We are planning to release Angular Wrapper supporting v8 of Handsontable at exactly the same time as 8.0.0 is released.

If nothing goes wrong we release both on 5.08.

**Comment by AMBudnik** [comment]
Hi @ottosson as the Handsontable for Angular is ready to use for v 8.0.0 of Handsontable can you confirm if the issue is still replicable?

**Comment by ottosson** [comment]
This does not seem to be an issue anymore.

![image](https://user-images.githubusercontent.com/3355320/92004008-fa868b00-ed41-11ea-88fd-13c302edf299.png)

Thanks!

**Comment by ottosson** [comment]
Hi! Sorry, I haven't had time to come back to this issue until now, and it seems to be working now.

But!

Now undoRedo.doneActions seems to be misspelled! "doneAction" in typings should be "doneActions" (currently `Handsontable.UndoRedo.doneAction`)

Maybe I should open this as a new issue.

**Comment by AMBudnik** [comment]
Thank you for the update @ottosson
